'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import store from "../../lib/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

// export const metadata ={
//   title:"TRICK TALK",
//   description:"Generated by create Next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
         <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
